on: push
name: Test
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cedx/setup-dart@v2
      - run: pub get
      - run: dartanalyzer bin lib test
      - run: dartfmt -n --set-exit-if-changed bin lib test
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cedx/setup-dart@v2
      - run: pub get
      - run: pub run test
